---
- name: Ensure prerequisite packages are present (Debian)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - python3-pip
    state: present
    update_cache: true

- name: Add Docker GPG key (Debian)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker repository (Debian)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker engine (Debian)
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure Docker service is started (Debian)
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add jenkins user to docker group (Debian)
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: true

- name: Configure Docker daemon to allow insecure registry (Debian)
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": ["{{ whanos_registry_host }}:443", "{{ whanos_registry_host }}"]
      }
    mode: "0644"
  notify: Restart docker

- name: Install Jenkins dependencies (Debian)
  ansible.builtin.apt:
    name:
      - openjdk-17-jdk
    state: present

- name: Add Jenkins GPG key (Debian)
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: "0644"

- name: Add Jenkins repository (Debian)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install Jenkins (Debian)
  ansible.builtin.apt:
    name: jenkins
    state: present
