# syntax=docker/dockerfile:1.6
FROM maven:3.9.6-eclipse-temurin-21 AS build

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY . .

RUN mvn -DskipTests package

FROM eclipse-temurin:21-jre

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY --from=build /app/target/app.jar /app/target/app.jar

CMD ["java", "-jar", "target/app.jar"]
