---
- name: Ensure Docker prerequisites are present (Debian)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
    state: present
    update_cache: true

- name: Add Docker GPG key (Debian)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker repository (Debian)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker packages (Debian)
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Ensure containerd is running (Debian)
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true

- name: Ensure Docker service is running (Debian)
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Install htpasswd tool (Debian)
  ansible.builtin.apt:
    name: apache2-utils
    state: present
