apiVersion: v1
kind: Namespace
metadata:
  name: whanos-cicd
  labels:
    app.kubernetes.io/name: whanos-cicd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whanos-deployer
  namespace: whanos-cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whanos-deployer
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources:
      - "configmaps"
      - "secrets"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: whanos-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: whanos-deployer
subjects:
  - kind: ServiceAccount
    name: whanos-deployer
    namespace: whanos-cicd
