# syntax=docker/dockerfile:1.6
FROM node:20.9-alpine

SHELL ["/bin/bash", "-c"]

LABEL maintainer="whanos" \
      org.whanos.language="javascript"

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev || npm install --production

COPY . .

CMD ["node", "."]
